In [1]:
import pandas as pd
import json
import os
import numpy as np
import datetime

# Data Loading

In [5]:
try:
    df = pd.read_csv('../data/v20240401_v2_csv.csv', sep=';')
except Exception as e:
    print(f"An error occurred: {e}")

/var/folders/tt/59b1f78918g9z5zhcmxxssqm0000gn/T/ipykernel_86735/3856999617.py:2: DtypeWarning: Columns (11,13,14,15,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/v20240401_v2_csv.csv', sep=';')

In [6]:
df.shape

(5573516, 38)

In [3]:
#Rename column in english
df.columns = [
    'Building_admission_date',  # Pand_opnamedatum
    'Building_admission_type',  # Pand_opnametype
    'Building_status',  # Pand_status
    'Building_calculation_type',  # Pand_berekeningstype
    'Building_energy_index',  # Pand_energieindex
    'Building_energy_class',  # Pand_energieklasse
    'Building_energy_label_is_private',  # Pand_energielabel_is_prive
    'Building_based_on_reference_building',  # Pand_is_op_basis_van_referentie_gebouw
    'Building_class',  # Pand_gebouwklasse
    'Measurement_valid_until',  # Meting_geldig_tot
    'Building_registration_date',  # Pand_registratiedatum
    'Building_postcode',  # Pand_postcode
    'Building_house_number',  # Pand_huisnummer
    'Building_house_letter',  # Pand_huisletter
    'Building_house_number_addition',  # Pand_huisnummertoevoeging
    'Building_detail_designation',  # Pand_detailaanduiding
    'Building_bag_residence_object_id',  # Pand_bagverblijfsobjectid
    'Building_bag_mooring_place_id',  # Pand_bagligplaatsid
    'Building_bag_standing_place_id',  # Pand_bagstandplaatsid
    'Building_bag_building_id',  # Pand_bagpandid
    'Building_type',  # Pand_gebouwtype
    'Building_subtype',  # Pand_gebouwsubtype
    'Building_project_name',  # Pand_projectnaam
    'Building_project_object',  # Pand_projectobject
    'Building_SBI_code',  # Pand_SBIcode
    'Building_usable_floor_area_thermal_zone',  # Pand_gebruiksoppervlakte_thermische_zone
    'Building_energy_requirement',  # Pand_energiebehoefte
    'Building_requirement_energy_requirement',  # Pand_eis_energiebehoefte
    'Building_primary_fossil_energy',  # Pand_primaire_fossiele_energie
    'Building_requirement_primary_fossil_energy',  # Pand_eis_primaire_fossiele_energie
    'Building_primary_fossil_energy_EMG_standard',  # Pand_primaire_fossiele_energie_EMG_forfaitair
    'Building_share_renewable_energy',  # Pand_aandeel_hernieuwbare_energie
    'Building_requirement_share_renewable_energy',  # Pand_eis_aandeel_hernieuwbare_energie
    'Building_share_renewable_energy_EMG_standard',  # Pand_aandeel_hernieuwbare_energie_EMG_forfaitair
    'Building_temperature_exceedance',  # Pand_temperatuuroverschrijding
    'Building_requirement_temperature_exceedance',  # Pand_eis_temperatuuroverschrijding
    'Building_heat_demand',  # Pand_warmtebehoefte LDD
    'Building_energy_index_with_EMG_standard'  # Pand_energieindex_met_EMG_forfaitair
]

#Add registration year
df['Building_registration_year'] = df['Building_registration_date'].apply(lambda date: int(str(date)[:4]))
#Add Postcode number 
df = df.dropna(subset=['Building_postcode'])
df['Building_postcode_num'] = df['Building_postcode'].apply(lambda postcode: int(str(postcode)[:4]))
df['Building_postcode_num'].unique()

array([1011, 1012, 1013, ..., 9997, 9998, 9999])

In [4]:
num_columns = list(df.select_dtypes(include=['int64', 'float64']).columns)
num_columns

['Building_admission_date',
 'Building_energy_index',
 'Building_energy_label_is_private',
 'Building_based_on_reference_building',
 'Measurement_valid_until',
 'Building_registration_date',
 'Building_house_number',
 'Building_bag_residence_object_id',
 'Building_bag_mooring_place_id',
 'Building_bag_standing_place_id',
 'Building_bag_building_id',
 'Building_SBI_code',
 'Building_usable_floor_area_thermal_zone',
 'Building_energy_requirement',
 'Building_requirement_energy_requirement',
 'Building_primary_fossil_energy',
 'Building_requirement_primary_fossil_energy',
 'Building_primary_fossil_energy_EMG_standard',
 'Building_share_renewable_energy',
 'Building_requirement_share_renewable_energy',
 'Building_share_renewable_energy_EMG_standard',
 'Building_temperature_exceedance',
 'Building_requirement_temperature_exceedance',
 'Building_heat_demand',
 'Building_energy_index_with_EMG_standard',
 'Building_registration_year',
 'Building_postcode_num']

In [5]:
df.select_dtypes(include=['object']).columns

Index(['Building_admission_type', 'Building_status',
       'Building_calculation_type', 'Building_energy_class', 'Building_class',
       'Building_postcode', 'Building_house_letter',
       'Building_house_number_addition', 'Building_detail_designation',
       'Building_type', 'Building_subtype', 'Building_project_name',
       'Building_project_object'],
      dtype='object')

# Data Exploration

In [8]:
df['Building_bag_building_id'].count()

1511521

In [6]:
#Create ams dataset (11-- postcodes still need to be added)
df_ams = df[df['Building_postcode_num'].isin(list(range(1000, 1113, 1)))]
df_ams

,Building_admission_date,Building_admission_type,Building_status,Building_calculation_type,Building_energy_index,Building_energy_class,Building_energy_label_is_private,Building_based_on_reference_building,Building_class,Measurement_valid_until,...,Building_primary_fossil_energy_EMG_standard,Building_share_renewable_energy,Building_requirement_share_renewable_energy,Building_share_renewable_energy_EMG_standard,Building_temperature_exceedance,Building_requirement_temperature_exceedance,Building_heat_demand,Building_energy_index_with_EMG_standard,Building_registration_year,Building_postcode_num
269217,20211007,Basisopname,Bestaand,NTA 8800:2020 (basisopname utiliteitsbouw),NaN,C,NaN,0,U,20311007,...,220.06,0.0,NaN,0.0,0.0,NaN,112.11,NaN,2021,1011
269218,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,55.98,54.0,NaN,NaN,0.0,NaN,44.16,NaN,2022,1011
269219,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,56.83,55.4,NaN,NaN,0.0,NaN,46.42,NaN,2022,1011
269220,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,56.88,54.8,NaN,NaN,0.0,NaN,47.03,NaN,2022,1011
269221,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A+++,NaN,0,W,20320512,...,28.53,81.0,NaN,NaN,0.0,NaN,68.95,NaN,2022,1011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629888,20180531,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.52,A,NaN,0,W,20280531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.74,2018,1112
629889,20180531,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.66,A,NaN,0,W,20280531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96,2018,1112
629890,20180531,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.66,A,NaN,0,W,20280531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.94,2018,1112
629891,20180531,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.58,A,NaN,0,W,20280531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,2018,1112
629892,20180531,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.66,A,NaN,0,W,20280531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,2018,1112

In [72]:
selected_columns = num_columns + ['Building_type'] + ['Building_subtype'] + ['Building_energy_class']

In [73]:
df_ams = df_ams[selected_columns]

In [74]:
gb = df_ams.groupby('Building_bag_residence_object_id')[['Building_registration_year', 'Building_energy_requirement', 
                                                         'Building_primary_fossil_energy', 'Building_heat_demand', 'Building_requirement_share_renewable_energy']].max()
#gb = gb.dropna()
gb

,Building_registration_year,Building_energy_requirement,Building_primary_fossil_energy,Building_heat_demand,Building_requirement_share_renewable_energy
Building_bag_residence_object_id,,,,,
0.000000e+00,2020,NaN,NaN,NaN,NaN
7.401000e+13,2014,NaN,NaN,NaN,NaN
1.190100e+14,2014,NaN,NaN,NaN,NaN
1.190100e+14,2014,NaN,NaN,NaN,NaN
1.530100e+14,2014,NaN,NaN,NaN,NaN
...,...,...,...,...,...
1.883010e+15,2014,NaN,NaN,NaN,NaN
1.883010e+15,2014,NaN,NaN,NaN,NaN
1.883010e+15,2014,NaN,NaN,NaN,NaN
1.883010e+15,2014,NaN,NaN,NaN,NaN
1.883010e+15,2014,NaN,NaN,NaN,NaN

In [75]:
gb2 = df_ams.groupby('Building_registration_year')[['Building_registration_year', 'Building_energy_requirement', 
                                                         'Building_primary_fossil_energy', 'Building_heat_demand', 'Building_requirement_share_renewable_energy']].count()
gb2

,Building_registration_year,Building_energy_requirement,Building_primary_fossil_energy,Building_heat_demand,Building_requirement_share_renewable_energy
Building_registration_year,,,,,
2014,9233,0,0,0,0
2015,27906,0,0,0,0
2016,30423,0,0,0,0
2017,35529,0,0,0,0
2018,40558,0,0,0,0
2019,50706,0,0,0,0
2020,59417,0,0,0,0
2021,24750,24703,24703,24703,502
2022,32903,32902,32902,32902,1172
2023,37961,37961,37961,37961,630
2024,11290,11290,11290,11290,360

In [76]:
gb3 = df_ams[df_ams.Building_registration_year >= 2021].groupby('Building_postcode_num')[['Building_registration_year', 'Building_energy_requirement', 
                                                         'Building_primary_fossil_energy', 'Building_heat_demand', 'Building_requirement_share_renewable_energy']].count()
gb3

,Building_registration_year,Building_energy_requirement,Building_primary_fossil_energy,Building_heat_demand,Building_requirement_share_renewable_energy
Building_postcode_num,,,,,
1011,937,929,929,929,11
1012,1102,1102,1102,1102,1
1013,2853,2852,2852,2852,3
1014,1120,1120,1120,1120,38
1015,1692,1692,1692,1692,1
...,...,...,...,...,...
1107,924,924,924,924,0
1108,121,121,121,121,0
1109,66,66,66,66,0
1111,1917,1916,1916,1916,1
1112,1358,1358,1358,1358,35

In [77]:
gb4 = df_ams.groupby('Building_postcode_num')[num_columns].apply(lambda x: (1-x.isna().sum()/len(x))*100)
gb4

,Building_admission_date,Building_energy_index,Building_energy_label_is_private,Building_based_on_reference_building,Measurement_valid_until,Building_registration_date,Building_house_number,Building_bag_residence_object_id,Building_bag_mooring_place_id,Building_bag_standing_place_id,...,Building_primary_fossil_energy_EMG_standard,Building_share_renewable_energy,Building_requirement_share_renewable_energy,Building_share_renewable_energy_EMG_standard,Building_temperature_exceedance,Building_requirement_temperature_exceedance,Building_heat_demand,Building_energy_index_with_EMG_standard,Building_registration_year,Building_postcode_num
Building_postcode_num,,,,,,,,,,,,,,,,,,,,,
1011,100.0,58.614473,0.0,100.0,100.0,100.0,100.0,99.587947,0.206026,0.0,...,22.328097,23.924800,0.283286,6.592841,23.924800,2.240536,23.924800,58.614473,100.0,100.0
1012,100.0,55.215876,0.0,100.0,100.0,100.0,100.0,99.222312,0.080451,0.0,...,27.728614,29.552159,0.026817,7.106463,29.552159,0.026817,29.552159,55.215876,100.0,100.0
1013,100.0,54.201815,0.0,100.0,100.0,100.0,100.0,99.412707,0.096103,0.0,...,29.535505,30.453817,0.032034,11.873999,30.453817,2.786973,30.453817,54.201815,100.0,100.0
1014,100.0,37.841945,0.0,100.0,100.0,100.0,100.0,99.962006,0.000000,0.0,...,42.211246,42.553191,1.443769,10.752280,42.553191,27.887538,42.553191,37.841945,100.0,100.0
1015,100.0,54.511462,0.0,100.0,100.0,100.0,100.0,99.122094,0.130060,0.0,...,25.573078,27.507722,0.016258,5.072346,27.507722,0.016258,27.507722,54.511462,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,100.0,58.269504,0.0,100.0,100.0,100.0,100.0,99.829787,0.000000,0.0,...,25.702128,26.212766,0.000000,9.219858,26.212766,0.000000,26.212766,58.269504,100.0,100.0
1108,100.0,35.225225,0.0,100.0,100.0,100.0,100.0,99.819820,0.000000,0.0,...,10.360360,10.900901,0.000000,3.603604,10.900901,0.000000,10.900901,35.225225,100.0,100.0
1109,100.0,43.478261,0.0,100.0,100.0,100.0,100.0,99.728261,0.000000,0.0,...,15.760870,17.934783,0.000000,8.423913,17.934783,0.000000,17.934783,43.478261,100.0,100.0
1111,100.0,29.514267,0.0,100.0,100.0,100.0,100.0,99.912873,0.000000,0.0,...,41.102156,41.733827,0.021782,17.708560,41.733827,0.021782,41.733827,29.514267,100.0,100.0
1112,100.0,65.612903,0.0,100.0,100.0,100.0,100.0,89.935484,0.016129,0.0,...,20.935484,21.903226,0.564516,10.645161,21.903226,2.274194,21.903226,65.612903,100.0,100.0

In [78]:
df[df['Building_bag_residence_object_id'] == 363010000547192][['Building_postcode','Building_house_number']]

       Building_postcode  Building_house_number
276090            1012TM                   30.0

In [79]:
df_ams['Building_energy_class'].unique()

array(['C', 'A++', 'A+++', 'A', 'A+', 'E', 'F', 'B', 'D', 'G', 'A++++',
       'A+++++', nan], dtype=object)

In [80]:
#Check outliers
outlier = df[df['Building_heat_demand'] == 10811801.41]
outlier

,Building_admission_date,Building_admission_type,Building_status,Building_calculation_type,Building_energy_index,Building_energy_class,Building_energy_label_is_private,Building_based_on_reference_building,Building_class,Measurement_valid_until,...,Building_primary_fossil_energy_EMG_standard,Building_share_renewable_energy,Building_requirement_share_renewable_energy,Building_share_renewable_energy_EMG_standard,Building_temperature_exceedance,Building_requirement_temperature_exceedance,Building_heat_demand,Building_energy_index_with_EMG_standard,Building_registration_year,Building_postcode_num
303722,20220704,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,G,NaN,0,W,20320704,...,NaN,0.0,NaN,NaN,1.62,NaN,10811801.41,NaN,2022,1017

# Dataset Preparation

In [81]:
df_residence = df_ams[['Building_bag_building_id','Building_type','Building_subtype','Building_postcode_num','Building_energy_class', 'Building_heat_demand', 'Building_share_renewable_energy', 'Building_primary_fossil_energy', 'Building_energy_requirement',
                          'Building_usable_floor_area_thermal_zone']].dropna(subset=['Building_bag_building_id','Building_energy_class', 'Building_heat_demand', 'Building_share_renewable_energy', 'Building_primary_fossil_energy', 'Building_energy_requirement',
                          'Building_usable_floor_area_thermal_zone'])
df_residence

,Building_bag_building_id,Building_type,Building_subtype,Building_postcode_num,Building_energy_class,Building_heat_demand,Building_share_renewable_energy,Building_primary_fossil_energy,Building_energy_requirement,Building_usable_floor_area_thermal_zone
269217,3.631000e+14,NaN,NaN,1011,C,112.11,0.0,220.06,132.74,1735.09
269218,3.631000e+14,Appartement,Tussenmidden,1011,A++,44.16,54.0,55.98,73.75,145.08
269219,3.631000e+14,Appartement,Tussenmidden,1011,A++,46.42,55.4,56.83,78.20,145.08
269220,3.631000e+14,Appartement,Tussenmidden,1011,A++,47.03,54.8,56.88,77.05,145.08
269221,3.631000e+14,Appartement,Tussendak,1011,A+++,68.95,81.0,28.53,110.55,292.63
...,...,...,...,...,...,...,...,...,...,...
629248,3.841000e+14,Appartement,Tussendak,1112,A,90.01,24.6,72.11,116.73,122.14
629249,3.841000e+14,Appartement,Hoekmidden,1112,A+,61.17,26.3,53.90,78.92,117.90
629250,3.841000e+14,Appartement,Hoekdak,1112,A,105.15,23.8,85.46,128.50,118.20
629664,3.841000e+14,Appartement,Tussenmidden,1112,A+,60.11,0.0,69.90,61.55,59.00
629723,3.841000e+14,Appartement,Hoekvloer,1112,A,90.13,0.0,118.44,95.28,66.40

In [82]:
df_residence['id'] = "NL.IMBAG.Pand.0" + df_residence['Building_bag_building_id'].astype('int64').astype(str)
df_residence

,Building_bag_building_id,Building_type,Building_subtype,Building_postcode_num,Building_energy_class,Building_heat_demand,Building_share_renewable_energy,Building_primary_fossil_energy,Building_energy_requirement,Building_usable_floor_area_thermal_zone,id
269217,3.631000e+14,NaN,NaN,1011,C,112.11,0.0,220.06,132.74,1735.09,NL.IMBAG.Pand.0363100012181958
269218,3.631000e+14,Appartement,Tussenmidden,1011,A++,44.16,54.0,55.98,73.75,145.08,NL.IMBAG.Pand.0363100012181959
269219,3.631000e+14,Appartement,Tussenmidden,1011,A++,46.42,55.4,56.83,78.20,145.08,NL.IMBAG.Pand.0363100012181959
269220,3.631000e+14,Appartement,Tussenmidden,1011,A++,47.03,54.8,56.88,77.05,145.08,NL.IMBAG.Pand.0363100012181959
269221,3.631000e+14,Appartement,Tussendak,1011,A+++,68.95,81.0,28.53,110.55,292.63,NL.IMBAG.Pand.0363100012181959
...,...,...,...,...,...,...,...,...,...,...,...
629248,3.841000e+14,Appartement,Tussendak,1112,A,90.01,24.6,72.11,116.73,122.14,NL.IMBAG.Pand.0384100000011622
629249,3.841000e+14,Appartement,Hoekmidden,1112,A+,61.17,26.3,53.90,78.92,117.90,NL.IMBAG.Pand.0384100000011622
629250,3.841000e+14,Appartement,Hoekdak,1112,A,105.15,23.8,85.46,128.50,118.20,NL.IMBAG.Pand.0384100000011622
629664,3.841000e+14,Appartement,Tussenmidden,1112,A+,60.11,0.0,69.90,61.55,59.00,NL.IMBAG.Pand.0384100000011455
629723,3.841000e+14,Appartement,Hoekvloer,1112,A,90.13,0.0,118.44,95.28,66.40,NL.IMBAG.Pand.0384100000011437

In [83]:
# Assuming 'ids' is a set of your 30,000 IDs
ids = set(df_residence['id'].unique().tolist())

# Directory containing your city.json files
directory = 'data/cityjson/'

# Dictionary to store the retrieved data
retrieved_data = {}

# Iterate through each file in the directory
for filename in os.listdir(directory):
    if filename.endswith('.city.json'):
        with open(os.path.join(directory, filename), 'r', encoding='utf-8') as file:
            print(f"Processing {filename}...")
            data = json.load(file)

            # Check each ID in the set against this file's data
            for building_id in list(ids):  # Use list to avoid RuntimeError for set size change during iteration
                if building_id in data['CityObjects']:
                    #print(f"Building {building_id} being processed...")
                    attributes = data['CityObjects'][building_id]['attributes']
                    oorspronkelijkbouwjaar = attributes.get('oorspronkelijkbouwjaar')
                    b3_volume_lod22 = attributes.get('b3_volume_lod22')
                    b3_bouwlagen = attributes.get('b3_bouwlagen')
                    b3_dak_type = attributes.get('b3_dak_type')
                    b3_kas_warenhuis = attributes.get('b3_kas_warenhuis')
                    geographical_extent = data['CityObjects'][building_id].get('geographicalExtent', [])

                    # Store the retrieved data
                    retrieved_data[building_id] = {
                        'id': building_id,
                        'oorspronkelijkbouwjaar': oorspronkelijkbouwjaar,
                        'b3_volume_lod22': b3_volume_lod22,
                        'b3_bouwlagen': b3_bouwlagen,
                        'b3_dak_type': b3_dak_type,
                        'b3_kas_warenhuis': b3_kas_warenhuis,
                        'geographicalExtent': geographical_extent
                        
                    }

                    # Remove the found ID from the set to avoid unnecessary future searches
                    ids.remove(building_id)

            # Optional: Early exit if all IDs are found
            if not ids:
                break

# At this point, 'retrieved_data' contains the data for all found IDs

Processing 10-434-716.city.json...
Processing 9-416-712.city.json...
Processing 9-424-728.city.json...
Processing 10-420-692.city.json...
Processing 10-430-716.city.json...
Processing 10-432-718.city.json...
Processing 7-400-688.city.json...
Processing 9-424-692.city.json...
Processing 7-464-672.city.json...
Processing 9-412-712.city.json...
Processing 9-420-704.city.json...
Processing 10-432-720.city.json...
Processing 9-452-688.city.json...
Processing 9-440-716.city.json...
Processing 9-436-720.city.json...
Processing 9-424-704.city.json...
Processing 8-432-688.city.json...
Processing 10-428-714.city.json...
Processing 9-444-716.city.json...
Processing 8-392-712.city.json...
Processing 10-420-694.city.json...
Processing 10-426-720.city.json...
Processing 8-400-736.city.json...
Processing 8-440-680.city.json...
Processing 9-468-688.city.json...
Processing 9-440-728.city.json...
Processing 9-416-700.city.json...
Processing 9-424-740.city.json...
Processing 9-408-720.city.json...
Processing 9-448-696.city.json...
Processing 9-444-728.city.json...
Processing 9-432-732.city.json...
Processing 8-448-712.city.json...
Processing 10-422-718.city.json...
Processing 10-420-716.city.json...
Processing 9-400-708.city.json...
Processing 9-444-704.city.json...
Processing 10-428-712.city.json...
Processing 7-384-688.city.json...
Processing 8-456-688.city.json...
Processing 9-440-704.city.json...
Processing 9-404-708.city.json...
Processing 10-424-716.city.json...
Processing 10-426-718.city.json...
Processing 9-436-732.city.json...
Processing 8-472-696.city.json...
Processing 9-448-700.city.json...
Processing 9-416-696.city.json...
Processing 8-456-696.city.json...
Processing 9-404-716.city.json...
Processing 8-472-688.city.json...
Processing 10-426-712.city.json...
Processing 10-430-722.city.json...
Processing 9-420-708.city.json...
Processing 9-416-688.city.json...
Processing 9-400-716.city.json...
Processing 10-428-718.city.json...
Processing 9-424-708.city.json...
Processing 10-434-722.city.json...
Processing 9-408-712.city.json...
Processing 10-428-720.city.json...
Processing 9-464-692.city.json...
Processing 9-448-688.city.json...
Processing 9-424-724.city.json...
Processing 9-420-724.city.json...
Processing 8-400-728.city.json...
Processing 10-432-714.city.json...
Processing 8-384-728.city.json...
Processing 9-416-720.city.json...
Processing 8-432-696.city.json...
Processing 9-444-708.city.json...
Processing 9-400-704.city.json...
Processing 9-412-720.city.json...
Processing 9-452-696.city.json...
Processing 9-404-704.city.json...
Processing 9-440-708.city.json...
Processing 10-426-714.city.json...
Processing 10-430-724.city.json...
Processing 9-428-732.city.json...
Processing 9-436-712.city.json...
Processing 10-432-712.city.json...
Processing 10-424-722.city.json...
Processing 8-392-720.city.json...
Processing 9-428-688.city.json...
Processing 8-456-712.city.json...
Processing 10-428-726.city.json...
Processing 8-384-704.city.json...
Processing 9-452-700.city.json...
Processing 8-440-736.city.json...
Processing 9-424-736.city.json...
Processing 10-430-714.city.json...
Processing 8-408-736.city.json...
Processing 9-428-740.city.json...
Processing 8-448-680.city.json...
Processing 10-434-714.city.json...
Processing 9-448-692.city.json...
Processing 9-464-688.city.json...
Processing 9-408-724.city.json...
Processing 9-416-704.city.json...
Processing 8-392-728.city.json...
Processing 8-424-696.city.json...
Processing 9-432-736.city.json...
Processing 10-428-716.city.json...
Processing 8-384-720.city.json...
Processing 9-436-736.city.json...
Processing 10-432-722.city.json...
Processing 10-424-712.city.json...
Processing 9-416-692.city.json...
Processing 9-420-712.city.json...
Processing 7-384-736.city.json...
Processing 9-428-692.city.json...
Processing 10-434-712.city.json...
Processing 9-432-708.city.json...
Processing 9-420-696.city.json...
Processing 9-416-716.city.json...
Processing 10-426-722.city.json...
Processing 9-436-708.city.json...
Processing 10-430-712.city.json...
Processing 9-428-728.city.json...
Processing 8-400-720.city.json...
Processing 9-412-716.city.json...
Processing 8-440-696.city.json...
Processing 9-392-704.city.json...
Processing 9-420-700.city.json...
Processing 10-424-714.city.json...
Processing 9-436-724.city.json...
Processing 9-428-704.city.json...
Processing 9-440-712.city.json...
Processing 8-416-728.city.json...
Processing 9-396-704.city.json...
Processing 9-444-712.city.json...
Processing 9-432-724.city.json...
Processing 8-448-704.city.json...
Processing 9-416-724.city.json...
Processing 9-432-740.city.json...
Processing 10-434-720.city.json...
Processing 9-452-692.city.json...
Processing 9-412-724.city.json...
Processing 10-430-720.city.json...
Processing 8-456-680.city.json...
Processing 9-436-740.city.json...
Processing 8-416-736.city.json...
Processing 9-436-716.city.json...
Processing 8-464-696.city.json...
Processing 7-448-720.city.json...
Processing 9-428-736.city.json...
Processing 8-440-688.city.json...
Processing 10-430-718.city.json...
Processing 9-424-688.city.json...
Processing 10-422-692.city.json...
Processing 10-432-716.city.json...
Processing 10-428-722.city.json...
Processing 9-424-732.city.json...
Processing 10-434-718.city.json...
Processing 9-420-688.city.json...
Processing 9-416-708.city.json...
Processing 9-436-728.city.json...
Processing 8-408-704.city.json...
Processing 7-464-704.city.json...
Processing 9-404-712.city.json...
Processing 9-428-708.city.json...
Processing 9-392-708.city.json...
Processing 10-424-718.city.json...
Processing 10-426-716.city.json...
Processing 9-400-712.city.json...
Processing 9-432-728.city.json...
Processing 9-408-716.city.json...
Processing 10-422-716.city.json...
Processing 8-432-680.city.json...
Processing 10-420-718.city.json...
Processing 9-396-708.city.json...
Processing 8-384-712.city.json...
Processing 10-428-724.city.json...
Processing 8-440-720.city.json...
Processing 9-444-732.city.json...
Processing 8-456-704.city.json...
Processing 9-432-704.city.json...
Processing 9-420-720.city.json...
Processing 8-408-728.city.json...
Processing 10-424-720.city.json...
Processing 10-422-694.city.json...
Processing 9-436-704.city.json...
Processing 9-440-732.city.json...
Processing 9-468-692.city.json...

In [84]:
len(ids), len(retrieved_data)

(1569, 34603)

In [85]:
df_residence.columns

Index(['Building_bag_building_id', 'Building_type', 'Building_subtype',
       'Building_postcode_num', 'Building_energy_class',
       'Building_heat_demand', 'Building_share_renewable_energy',
       'Building_primary_fossil_energy', 'Building_energy_requirement',
       'Building_usable_floor_area_thermal_zone', 'id'],
      dtype='object')

In [86]:
missing_buildings_ids = df_residence[df_residence['id'].isin(ids)]['Building_bag_building_id'].values
missing_buildings = df_residence[df_residence['Building_bag_building_id'].isin(missing_buildings_ids)]

In [87]:
missing_buildings.groupby('Building_postcode_num')['Building_bag_building_id'].nunique().sort_values(ascending=False)

Building_postcode_num
1057    197
1111    170
1097    154
1058    140
1087    111
       ...
1074      1
1073      1
1052      1
1063      1
1017      1
Name: Building_bag_building_id, Length: 63, dtype: int64

A thousand building are missing. It's either because they are in between two tiles, or sometimes, data miss for one neighborhood. It is however negligeble as we have 30'000 buildings

In [88]:
df_residence[df_residence['Building_postcode_num'] == 1082].Building_bag_building_id.values[0]

363100012108994.0

In [89]:
np.unique(missing_buildings_ids)[1320]

363100012254946.0

# Merging dataset

In [90]:
df

,Building_admission_date,Building_admission_type,Building_status,Building_calculation_type,Building_energy_index,Building_energy_class,Building_energy_label_is_private,Building_based_on_reference_building,Building_class,Measurement_valid_until,...,Building_primary_fossil_energy_EMG_standard,Building_share_renewable_energy,Building_requirement_share_renewable_energy,Building_share_renewable_energy_EMG_standard,Building_temperature_exceedance,Building_requirement_temperature_exceedance,Building_heat_demand,Building_energy_index_with_EMG_standard,Building_registration_year,Building_postcode_num
269217,20211007,Basisopname,Bestaand,NTA 8800:2020 (basisopname utiliteitsbouw),NaN,C,NaN,0,U,20311007,...,220.06,0.0,NaN,0.0,0.0,NaN,112.11,NaN,2021,1011
269218,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,55.98,54.0,NaN,NaN,0.0,NaN,44.16,NaN,2022,1011
269219,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,56.83,55.4,NaN,NaN,0.0,NaN,46.42,NaN,2022,1011
269220,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A++,NaN,0,W,20320512,...,56.88,54.8,NaN,NaN,0.0,NaN,47.03,NaN,2022,1011
269221,20220512,Basisopname,Bestaand,NTA 8800:2022 (basisopname woningbouw),NaN,A+++,NaN,0,W,20320512,...,28.53,81.0,NaN,NaN,0.0,NaN,68.95,NaN,2022,1011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5573511,20201231,NaN,NaN,"Rekenmethodiek Definitief Energielabel, versie...",NaN,E,NaN,0,W,20301231,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,9999
5573512,20191030,NaN,NaN,"Rekenmethodiek Definitief Energielabel, versie...",NaN,A,NaN,0,W,20291030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,9999
5573513,20190126,NaN,NaN,"Nader Voorschrift, versie 1.0, 1 februari 2014...",0.93,A,NaN,0,W,20290126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,2019,9999
5573514,20201208,NaN,NaN,"Rekenmethodiek Definitief Energielabel, versie...",NaN,B,NaN,0,W,20301208,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,9999
5573515,20200817,NaN,NaN,"Rekenmethodiek Definitief Energielabel, versie...",NaN,E,NaN,0,W,20300817,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,9999

In [91]:
df_residence

,Building_bag_building_id,Building_type,Building_subtype,Building_postcode_num,Building_energy_class,Building_heat_demand,Building_share_renewable_energy,Building_primary_fossil_energy,Building_energy_requirement,Building_usable_floor_area_thermal_zone,id
269217,3.631000e+14,NaN,NaN,1011,C,112.11,0.0,220.06,132.74,1735.09,NL.IMBAG.Pand.0363100012181958
269218,3.631000e+14,Appartement,Tussenmidden,1011,A++,44.16,54.0,55.98,73.75,145.08,NL.IMBAG.Pand.0363100012181959
269219,3.631000e+14,Appartement,Tussenmidden,1011,A++,46.42,55.4,56.83,78.20,145.08,NL.IMBAG.Pand.0363100012181959
269220,3.631000e+14,Appartement,Tussenmidden,1011,A++,47.03,54.8,56.88,77.05,145.08,NL.IMBAG.Pand.0363100012181959
269221,3.631000e+14,Appartement,Tussendak,1011,A+++,68.95,81.0,28.53,110.55,292.63,NL.IMBAG.Pand.0363100012181959
...,...,...,...,...,...,...,...,...,...,...,...
629248,3.841000e+14,Appartement,Tussendak,1112,A,90.01,24.6,72.11,116.73,122.14,NL.IMBAG.Pand.0384100000011622
629249,3.841000e+14,Appartement,Hoekmidden,1112,A+,61.17,26.3,53.90,78.92,117.90,NL.IMBAG.Pand.0384100000011622
629250,3.841000e+14,Appartement,Hoekdak,1112,A,105.15,23.8,85.46,128.50,118.20,NL.IMBAG.Pand.0384100000011622
629664,3.841000e+14,Appartement,Tussenmidden,1112,A+,60.11,0.0,69.90,61.55,59.00,NL.IMBAG.Pand.0384100000011455
629723,3.841000e+14,Appartement,Hoekvloer,1112,A,90.13,0.0,118.44,95.28,66.40,NL.IMBAG.Pand.0384100000011437

In [92]:
retrieved_df = pd.DataFrame(list(retrieved_data.values()))
retrieved_df = retrieved_df.rename(columns={'oorspronkelijkbouwjaar': 'year', 'b3_volume_lod22': 'volume', 
                                           'b3_bouwlagen': 'floors', 'b3_dak_type': 'roof_type', 'b3_kas_warenhuis': 'greenhouse'})

In [93]:
df_residence.shape, retrieved_df.shape

((104507, 11), (34603, 7))

In [94]:
dataset = df_residence.merge(retrieved_df, on='id', how='left')
dataset

,Building_bag_building_id,Building_type,Building_subtype,Building_postcode_num,Building_energy_class,Building_heat_demand,Building_share_renewable_energy,Building_primary_fossil_energy,Building_energy_requirement,Building_usable_floor_area_thermal_zone,id,year,volume,floors,roof_type,greenhouse,geographicalExtent
0,3.631000e+14,NaN,NaN,1011,C,112.11,0.0,220.06,132.74,1735.09,NL.IMBAG.Pand.0363100012181958,1948.0,6891.854004,NaN,multiple horizontal,False,"[122184.046875, 487858.3125, 1.467000007629394..."
1,3.631000e+14,Appartement,Tussenmidden,1011,A++,44.16,54.0,55.98,73.75,145.08,NL.IMBAG.Pand.0363100012181959,1916.0,2149.765625,NaN,slanted,False,"[122198.2265625, 487857.5, 1.3890000581741333,..."
2,3.631000e+14,Appartement,Tussenmidden,1011,A++,46.42,55.4,56.83,78.20,145.08,NL.IMBAG.Pand.0363100012181959,1916.0,2149.765625,NaN,slanted,False,"[122198.2265625, 487857.5, 1.3890000581741333,..."
3,3.631000e+14,Appartement,Tussenmidden,1011,A++,47.03,54.8,56.88,77.05,145.08,NL.IMBAG.Pand.0363100012181959,1916.0,2149.765625,NaN,slanted,False,"[122198.2265625, 487857.5, 1.3890000581741333,..."
4,3.631000e+14,Appartement,Tussendak,1011,A+++,68.95,81.0,28.53,110.55,292.63,NL.IMBAG.Pand.0363100012181959,1916.0,2149.765625,NaN,slanted,False,"[122198.2265625, 487857.5, 1.3890000581741333,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104502,3.841000e+14,Appartement,Tussendak,1112,A,90.01,24.6,72.11,116.73,122.14,NL.IMBAG.Pand.0384100000011622,2021.0,55637.558594,NaN,multiple horizontal,False,"[125828.09375, 482246.75, -2.979997396469116, ..."
104503,3.841000e+14,Appartement,Hoekmidden,1112,A+,61.17,26.3,53.90,78.92,117.90,NL.IMBAG.Pand.0384100000011622,2021.0,55637.558594,NaN,multiple horizontal,False,"[125828.09375, 482246.75, -2.979997396469116, ..."
104504,3.841000e+14,Appartement,Hoekdak,1112,A,105.15,23.8,85.46,128.50,118.20,NL.IMBAG.Pand.0384100000011622,2021.0,55637.558594,NaN,multiple horizontal,False,"[125828.09375, 482246.75, -2.979997396469116, ..."
104505,3.841000e+14,Appartement,Tussenmidden,1112,A+,60.11,0.0,69.90,61.55,59.00,NL.IMBAG.Pand.0384100000011455,2020.0,44805.992188,NaN,multiple horizontal,False,"[125947.5234375, 482448.3125, -1.7599999904632..."
104506,3.841000e+14,Appartement,Hoekvloer,1112,A,90.13,0.0,118.44,95.28,66.40,NL.IMBAG.Pand.0384100000011437,2018.0,38293.121094,NaN,multiple horizontal,False,"[126005.6953125, 482394.03125, -2.453999996185..."

# Save Dataset

In [95]:
year = str(datetime.datetime.now().year)
month = str(datetime.datetime.now().month)
day = str(datetime.datetime.now().day)
hour = str(datetime.datetime.now().hour)
min = str(datetime.datetime.now().minute)
sec = str(datetime.datetime.now().second)
dt = year + month + day + hour + min + sec

In [96]:
dataset.to_csv(f'data/out/dataset_v{dt}')