In [2]:
import pandas as pd
import json
import os
import numpy as np
import datetime

# Data Loading

In [3]:
try:
    df = pd.read_csv('../data/nl_extract/bagadres-woning.csv', sep=';')
except Exception as e:
    print(f"An error occurred: {e}")

/var/folders/tt/59b1f78918g9z5zhcmxxssqm0000gn/T/ipykernel_73967/2092556776.py:2: DtypeWarning: Columns (1,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/nl_extract/bagadres-woning.csv', sep=';')

In [5]:
df = df[df['gemeente'] == 'Amsterdam']
df

,openbareruimtenaam,verkorteopenbareruimtenaam,openbareruimte_id,huisnummer,huisletter,huisnummertoevoeging,postcode,nummeraanduiding_id,buurtnaam,buurtcode,...,woningtype,omtrek_pand,verhouding_opp_vbo_opp_pnd,pandstatus,bouwjaar,uniq_key,pchnhlht,pchnhlht_uniek,pchn_uniek,rangorde_pchn
0,De Ruijterkade,NaN,363300000006091,99,NaN,NaN,1011AB,363200013025017,Oosterdokseiland,BU0363AF01,...,NaN,55.0,1.61,Pand in gebruik,2022.0,1011AB-99-0-0-0363300000006091,1011AB-99-0-0,1.0,1.0,1
1,De Ruijterkade,NaN,363300000006091,105,NaN,1,1011AB,363200000081086,Oosterdokseiland,BU0363AF01,...,NaN,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-1-0363300000006091,1011AB-105-0-1,1.0,0.0,3
2,De Ruijterkade,NaN,363300000006091,105,NaN,2,1011AB,363200000081087,Oosterdokseiland,BU0363AF01,...,Appartement,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-2-0363300000006091,1011AB-105-0-2,1.0,0.0,1
3,De Ruijterkade,NaN,363300000006091,105,NaN,3,1011AB,363200000081088,Oosterdokseiland,BU0363AF01,...,Appartement,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-3-0363300000006091,1011AB-105-0-3,1.0,0.0,2
4,De Ruijterkade,NaN,363300000006091,105,NaN,H,1011AB,363200000081085,Oosterdokseiland,BU0363AF01,...,NaN,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-H-0363300000006091,1011AB-105-0-H,1.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765315,tt. Vasumweg,NaN,363300000005872,34,C,NaN,NaN,363200012141999,NDSM terrein,BU0363NB03,...,NaN,384.0,10.69,Pand in gebruik,2022.0,0-34-C-0-0363300000005872,0-34-C-0,NaN,NaN,886
9765316,tt. Vasumweg,NaN,363300000005872,38,B,NaN,NaN,363200012141995,NDSM terrein,BU0363NB03,...,NaN,384.0,10.69,Pand in gebruik,2022.0,0-38-B-0-0363300000005872,0-38-B-0,NaN,NaN,991
9765317,tt. Vasumweg,NaN,363300000005872,38,C,NaN,NaN,363200012141994,NDSM terrein,BU0363NB03,...,NaN,384.0,10.69,Pand in gebruik,2022.0,0-38-C-0-0363300000005872,0-38-C-0,NaN,NaN,1020
9765318,tt. Vasumweg,NaN,363300000005872,38,D,NaN,NaN,363200012141993,NDSM terrein,BU0363NB03,...,NaN,384.0,10.69,Pand in gebruik,2022.0,0-38-D-0-0363300000005872,0-38-D-0,NaN,NaN,1080
9765319,tt. Vasumweg,NaN,363300000005872,69,NaN,NaN,NaN,363200012104257,NDSM terrein,BU0363NB03,...,NaN,289.0,1.21,Pand in gebruik,2019.0,0-69-0-0-0363300000005872,0-69-0-0,NaN,NaN,118

In [7]:
df.woningtype.unique()

array([nan, 'Appartement', 'Tussen of geschakelde woning',
       'Vrijstaande woning', 'Hoekwoning', 'Tweeonder1kap'], dtype=object)

In [22]:
df.groupby('Building_type').count()

,Building_admission_date,Building_admission_type,Building_status,Building_calculation_type,Building_energy_index,Building_energy_class,Building_energy_label_is_private,Building_based_on_reference_building,Building_class,Measurement_valid_until,...,Building_requirement_primary_fossil_energy,Building_primary_fossil_energy_EMG_standard,Building_share_renewable_energy,Building_requirement_share_renewable_energy,Building_share_renewable_energy_EMG_standard,Building_temperature_exceedance,Building_requirement_temperature_exceedance,Building_heat_demand,Building_energy_index_with_EMG_standard,Building_registration_year
Building_type,,,,,,,,,,,,,,,,,,,,,
Appartement,839012,839012,839012,839012,0,814568,0,839012,839012,839012,...,23918,692421,839012,23918,215653,839012,235070,839012,0,839012
Flatwoning (overig),1234593,0,0,1234593,855266,1234593,0,1234593,1234593,1234593,...,0,0,0,0,0,0,0,0,855266,1234593
Galerijwoning,68333,0,0,68333,68333,68333,0,68333,68333,68333,...,0,0,0,0,0,0,0,0,68333,68333
Logieswoning,42560,42560,42560,42560,0,42560,0,42560,42560,42560,...,7413,32594,42560,7413,1769,42560,7413,42560,0,42560
Maisonnette,169479,0,0,169479,123753,169479,0,169479,169479,169479,...,0,0,0,0,0,0,0,0,123753,169479
Portiekwoning,27023,0,0,27023,27023,27023,0,27023,27023,27023,...,0,0,0,0,0,0,0,0,27023,27023
Rijwoning hoek,197425,197425,197425,197425,0,197425,0,197425,197425,197425,...,39720,159206,197425,39720,54671,197425,39720,197425,0,197425
Rijwoning tussen,1310865,367652,367652,1310865,440769,1310865,0,1310865,1310865,1310865,...,62146,309206,367652,62146,105513,367652,62146,367652,440769,1310865
Twee-onder-een-kap / rijwoning hoek,826770,0,0,826770,281152,826770,0,826770,826770,826770,...,0,0,0,0,0,0,0,0,281152,826770
Twee-onder-één-kap,103758,103758,103758,103758,0,103758,0,103758,103758,103758,...,26314,73942,103758,26314,25918,103758,26314,103758,0,103758
Vrijstaande woning,522056,125611,125611,522056,19621,522056,0,522056,522056,522056,...,33378,79993,125611,33378,29337,125611,33378,125611,19621,522056
Woonboot bestaande ligplaats,748,748,748,748,0,748,0,748,748,748,...,159,503,748,159,179,748,159,748,0,748
Woonboot nieuwe ligplaats,184,184,184,184,0,184,0,184,184,184,...,100,88,184,100,27,184,100,184,0,184
Woongebouw met niet-zelfstandige woonruimte,1098,913,913,1098,185,906,0,1098,1098,1098,...,213,706,913,213,212,913,215,913,185,1098
Woonwagen,954,954,954,954,0,954,0,954,954,954,...,276,731,954,276,109,954,276,954,0,954

In [8]:
# Translation dictionary
translation_dict = {
    'Appartement': 'Apartment',
    'Tussen of geschakelde woning': 'Terraced or semi-detached house',
    'Vrijstaande woning': 'Detached house',
    'Hoekwoning': 'Corner house',
    'Tweeonder1kap': 'Semi-detached house',
    np.nan: np.nan  # To handle NaN values
}

# Translation function
def translate_property_type(property_type):
    return translation_dict.get(property_type, property_type)

# Apply the function to the DataFrame
df['property_type'] = df['woningtype'].apply(translate_property_type)

In [11]:
df

,openbareruimtenaam,verkorteopenbareruimtenaam,openbareruimte_id,huisnummer,huisletter,huisnummertoevoeging,postcode,nummeraanduiding_id,buurtnaam,buurtcode,...,omtrek_pand,verhouding_opp_vbo_opp_pnd,pandstatus,bouwjaar,uniq_key,pchnhlht,pchnhlht_uniek,pchn_uniek,rangorde_pchn,property_type
0,De Ruijterkade,NaN,363300000006091,99,NaN,NaN,1011AB,363200013025017,Oosterdokseiland,BU0363AF01,...,55.0,1.61,Pand in gebruik,2022.0,1011AB-99-0-0-0363300000006091,1011AB-99-0-0,1.0,1.0,1,NaN
1,De Ruijterkade,NaN,363300000006091,105,NaN,1,1011AB,363200000081086,Oosterdokseiland,BU0363AF01,...,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-1-0363300000006091,1011AB-105-0-1,1.0,0.0,3,NaN
2,De Ruijterkade,NaN,363300000006091,105,NaN,2,1011AB,363200000081087,Oosterdokseiland,BU0363AF01,...,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-2-0363300000006091,1011AB-105-0-2,1.0,0.0,1,Apartment
3,De Ruijterkade,NaN,363300000006091,105,NaN,3,1011AB,363200000081088,Oosterdokseiland,BU0363AF01,...,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-3-0363300000006091,1011AB-105-0-3,1.0,0.0,2,Apartment
4,De Ruijterkade,NaN,363300000006091,105,NaN,H,1011AB,363200000081085,Oosterdokseiland,BU0363AF01,...,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-H-0363300000006091,1011AB-105-0-H,1.0,0.0,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765315,tt. Vasumweg,NaN,363300000005872,34,C,NaN,NaN,363200012141999,NDSM terrein,BU0363NB03,...,384.0,10.69,Pand in gebruik,2022.0,0-34-C-0-0363300000005872,0-34-C-0,NaN,NaN,886,NaN
9765316,tt. Vasumweg,NaN,363300000005872,38,B,NaN,NaN,363200012141995,NDSM terrein,BU0363NB03,...,384.0,10.69,Pand in gebruik,2022.0,0-38-B-0-0363300000005872,0-38-B-0,NaN,NaN,991,NaN
9765317,tt. Vasumweg,NaN,363300000005872,38,C,NaN,NaN,363200012141994,NDSM terrein,BU0363NB03,...,384.0,10.69,Pand in gebruik,2022.0,0-38-C-0-0363300000005872,0-38-C-0,NaN,NaN,1020,NaN
9765318,tt. Vasumweg,NaN,363300000005872,38,D,NaN,NaN,363200012141993,NDSM terrein,BU0363NB03,...,384.0,10.69,Pand in gebruik,2022.0,0-38-D-0-0363300000005872,0-38-D-0,NaN,NaN,1080,NaN
9765319,tt. Vasumweg,NaN,363300000005872,69,NaN,NaN,NaN,363200012104257,NDSM terrein,BU0363NB03,...,289.0,1.21,Pand in gebruik,2019.0,0-69-0-0-0363300000005872,0-69-0-0,NaN,NaN,118,NaN

In [23]:
try:
    data = pd.read_csv('../data/nl_extract.csv')
except Exception as e:
    print(f"An error occurred: {e}")

In [28]:
df_nl = data[['pand_id', 'woningtype']]
df_nl.columns = ['Building_bag_building_id', 'woningtype']
df_nl

     Building_bag_building_id   woningtype
0                3.631000e+14          NaN
1                3.631000e+14  Appartement
2                3.631000e+14  Appartement
3                3.631000e+14          NaN
4                3.631000e+14          NaN
..                        ...          ...
294              7.481000e+14          NaN
295              7.481000e+14          NaN
296              7.481000e+14          NaN
297              7.481000e+14          NaN
298              7.481000e+14          NaN

[299 rows x 2 columns]

In [29]:
out = df_nl.merge(df, how='left', on='Building_bag_building_id')[['Building_bag_building_id', 'woningtype', 'Building_type','Building_subtype']]
out

         Building_bag_building_id   woningtype Building_type Building_subtype
0                    3.631000e+14          NaN           NaN              NaN
1                    3.631000e+14  Appartement           NaN              NaN
2                    3.631000e+14  Appartement           NaN              NaN
3                    3.631000e+14          NaN           NaN              NaN
4                    3.631000e+14          NaN           NaN              NaN
...                           ...          ...           ...              ...
4050088              7.481000e+14          NaN           NaN              NaN
4050089              7.481000e+14          NaN           NaN              NaN
4050090              7.481000e+14          NaN           NaN              NaN
4050091              7.481000e+14          NaN           NaN              NaN
4050092              7.481000e+14          NaN           NaN              NaN

[4050093 rows x 4 columns]

In [26]:
df['Building_bag_building_id']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
           ..
5573511   NaN
5573512   NaN
5573513   NaN
5573514   NaN
5573515   NaN
Name: Building_bag_building_id, Length: 5573516, dtype: float64

In [27]:
df_nl[df_nl['Building_bag_building_id'] == 363100012181958]

Empty DataFrame
Columns: [Building_bag_building_id, woningtype]
Index: []

In [6]:
df['woningtype'].unique()

array([nan, 'Appartement', 'Tussen of geschakelde woning',
       'Vrijstaande woning', 'Hoekwoning', 'Tweeonder1kap'], dtype=object)