In [4]:
import pandas as pd

In [5]:
FILE_PATH_ZH = 'data/weather/Zuerich-SMA_2016.epw'
FILE_PATH_AMS = 'data/weather/NLD_NH_Amsterdam-Schipol.AP.062400_TMYx.2007-2021/NLD_NH_Amsterdam-Schipol.AP.062400_TMYx.2007-2021.epw'

In [3]:
column_names = [
    "Year", "Month", "Day", "Hour", "Minute", "Data Source and Uncertainty Flags",
    "Dry Bulb Temperature (°C)", "Dew Point Temperature (°C)", "Relative Humidity (%)",
    "Atmospheric Station Pressure (Pa)", "Extraterrestrial Horizontal Radiation (Wh/m^2)",
    "Extraterrestrial Direct Normal Radiation (Wh/m^2)", "Horizontal Infrared Radiation Intensity (Wh/m^2)",
    "Global Horizontal Radiation (Wh/m^2)", "Direct Normal Radiation (Wh/m^2)",
    "Diffuse Horizontal Radiation (Wh/m^2)", "Global Horizontal Illuminance (lux)",
    "Direct Normal Illuminance (lux)", "Diffuse Horizontal Illuminance (lux)",
    "Zenith Luminance (cd/m^2)", "Wind Direction (°)", "Wind Speed (m/s)",
    "Total Sky Cover (tenths)", "Opaque Sky Cover (tenths)", "Visibility (km)",
    "Ceiling Height (m)", "Present Weather Observation", "Present Weather Codes",
    "Precipitable Water (mm)", "Aerosol Optical Depth", "Snow Depth (cm)",
    "Days Since Last Snowfall", "Albedo", "Liquid Precipitation Depth (mm)"
]
len(column_names)

34

In [9]:
df_zh = pd.read_csv(FILE_PATH_ZH, skiprows=8, header=None, names=column_names, index_col=False)
df_ams = pd.read_csv(FILE_PATH_AMS, skiprows=8, header=None, names=column_names, index_col=False)
df_zh

/var/folders/tt/59b1f78918g9z5zhcmxxssqm0000gn/T/ipykernel_35035/572383197.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_zh = pd.read_csv(FILE_PATH_ZH, skiprows=8, header=None, names=column_names, index_col=False)
/var/folders/tt/59b1f78918g9z5zhcmxxssqm0000gn/T/ipykernel_35035/572383197.py:2: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_ams = pd.read_csv(FILE_PATH_AMS, skiprows=8, header=None, names=column_names, index_col=False)

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature (°C),Dew Point Temperature (°C),Relative Humidity (%),Atmospheric Station Pressure (Pa),...,Visibility (km),Ceiling Height (m),Present Weather Observation,Present Weather Codes,Precipitable Water (mm),Aerosol Optical Depth,Snow Depth (cm),Days Since Last Snowfall,Albedo,Liquid Precipitation Depth (mm)
0,2016,1,1,1,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,5.0,4.8,99,95919,...,9999,99999,9,999999999,13,0.058,0,4,0.2,0.0
1,2016,1,1,2,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,5.0,4.8,99,95919,...,9999,99999,9,999999999,13,0.058,0,4,0.2,0.0
2,2016,1,1,3,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,5.0,4.7,98,95938,...,9999,99999,9,999999999,13,0.058,0,4,0.2,0.1
3,2016,1,1,4,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,5.1,4.9,99,95987,...,9999,99999,9,999999999,13,0.058,0,4,0.2,0.0
4,2016,1,1,5,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,5.2,4.8,97,96026,...,9999,99999,9,999999999,13,0.058,0,4,0.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2016,12,31,20,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,-3.0,-3.6,96,96424,...,9999,99999,9,999999999,7,0.052,0,13,0.2,0.0
8780,2016,12,31,21,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,-3.4,-3.5,99,96349,...,9999,99999,9,999999999,7,0.052,0,13,0.2,0.0
8781,2016,12,31,22,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,-3.3,-3.3,100,96295,...,9999,99999,9,999999999,7,0.052,0,13,0.2,0.0
8782,2016,12,31,23,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,-2.8,-3.2,97,96252,...,9999,99999,9,999999999,7,0.052,0,13,0.2,0.0
8783,2016,12,31,24,60,*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?*?,-2.9,-3.3,97,96222,...,9999,99999,9,999999999,7,0.052,0,13,0.2,0.0

In [8]:
df_ams

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature (°C),Dew Point Temperature (°C),Relative Humidity (%),Atmospheric Station Pressure (Pa),...,Visibility (km),Ceiling Height (m),Present Weather Observation,Present Weather Codes,Precipitable Water (mm),Aerosol Optical Depth,Snow Depth (cm),Days Since Last Snowfall,Albedo,Liquid Precipitation Depth (mm)
2015,1,1,1,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,1.8,89,103401,0,...,660,9,999999999,12,0.085,0,88,0.1,0.0,0.0
2015,1,1,2,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,2.4,93,101365,0,...,627,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2015,1,1,3,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.4,1.4,87,101365,0,...,534,9,999999999,11,0.085,0,88,0.1,0.0,0.0
2015,1,1,4,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.3,2.1,92,103311,0,...,546,9,999999999,12,0.085,0,88,0.1,0.0,0.0
2015,1,1,5,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.1,1.2,87,101365,0,...,537,9,999999999,11,0.085,0,88,0.1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014,12,31,20,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,0,...,671,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2014,12,31,21,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,0,...,732,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2014,12,31,22,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.6,2.4,92,103491,0,...,690,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2014,12,31,23,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,0,...,552,9,999999999,12,0.085,0,88,0.1,0.0,0.0
2014,12,31,24,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,0,...,503,9,999999999,12,0.085,0,88,0.1,0.0,0.0

In [9]:
data = pd.read_csv(FILE_PATH_AMS, skiprows=8, header=None, delimiter=',', engine='python')
data

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,2015,1,1,1,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,1.8,89,103401,...,660,9,999999999,12,0.085,0,88,0.1,0.0,0.0
1,2015,1,1,2,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,2.4,93,101365,...,627,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2,2015,1,1,3,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.4,1.4,87,101365,...,534,9,999999999,11,0.085,0,88,0.1,0.0,0.0
3,2015,1,1,4,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.3,2.1,92,103311,...,546,9,999999999,12,0.085,0,88,0.1,0.0,0.0
4,2015,1,1,5,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.1,1.2,87,101365,...,537,9,999999999,11,0.085,0,88,0.1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2014,12,31,20,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,...,671,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8756,2014,12,31,21,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,...,732,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8757,2014,12,31,22,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.6,2.4,92,103491,...,690,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8758,2014,12,31,23,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,...,552,9,999999999,12,0.085,0,88,0.1,0.0,0.0
8759,2014,12,31,24,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,...,503,9,999999999,12,0.085,0,88,0.1,0.0,0.0

In [10]:

# Modify the year column to 2016
data[0] = 2016
data

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,2016,1,1,1,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,1.8,89,103401,...,660,9,999999999,12,0.085,0,88,0.1,0.0,0.0
1,2016,1,1,2,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.5,2.4,93,101365,...,627,9,999999999,13,0.085,0,88,0.1,0.0,0.0
2,2016,1,1,3,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.4,1.4,87,101365,...,534,9,999999999,11,0.085,0,88,0.1,0.0,0.0
3,2016,1,1,4,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.3,2.1,92,103311,...,546,9,999999999,12,0.085,0,88,0.1,0.0,0.0
4,2016,1,1,5,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.1,1.2,87,101365,...,537,9,999999999,11,0.085,0,88,0.1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2016,12,31,20,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,...,671,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8756,2016,12,31,21,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,3.0,93,101365,...,732,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8757,2016,12,31,22,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,3.6,2.4,92,103491,...,690,9,999999999,13,0.085,0,88,0.1,0.0,0.0
8758,2016,12,31,23,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,...,552,9,999999999,12,0.085,0,88,0.1,0.0,0.0
8759,2016,12,31,24,0,?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9*9,4.0,2.0,87,101365,...,503,9,999999999,12,0.085,0,88,0.1,0.0,0.0

In [13]:

# Save the modified data to a new .epw file
new_file_path = 'data/weather/amsterdam_2007-2021.epw'
data.to_csv(new_file_path, sep=',', header=False, index=False)

print(f"File '{new_file_path}' has been created with the year column modified to 2016.")

File 'data/weather/amsterdam_2007-2021.epw' has been created with the year column modified to 2016.